port: "8000"

bot:
  messageTTLInMinutes: 1
  messageTTLInHours: 0
  outdatedMessagesSleepIntervalInHours: 10

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"
